name: Team awesome\'s approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Little E\'s Step 1
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approvalsMet"
